export const SITE_TITLE = 'Ace Website';
export const SITE_DESCRIPTION = 'Welcome to Ace Website';

export enum ContentType {
  CardLink = 'card-link',
  Video = 'video',
  None = 'none',
}

export const githubLink = 'https://github.com/ACE-NMAMIT/';
export const linkedinLink = 'https://www.linkedin.com/company/acenmamit/';
export const instagramLink = 'https://www.instagram.com/ace_nmamit/';

export const faculty = [
  { name: 'Dr. Niranjan N. Chiplunkar', position: 'Principal', image: 'prin' },
  { name: 'Dr. Jyothi Shetty', position: 'Professor & Head', image: 'hod' },
  { name: 'Mr. Piyush Goel', position: 'Pofessor of Practice', image: 't3' },
  { name: 'Dr. D K Sreekantha', position: 'Professor', image: 't4' },
  { name: 'Dr. P V Bhat ', position: 'Professor', image: 't5' },
  { name: 'Dr. Aravind C V', position: 'Professor', image: 't6' },
  { name: 'Dr. Sarika Hegde', position: 'Professor', image: 't7' },
  { name: 'Dr. Sudeepa K B', position: 'Associate Professor', image: 't8' },
  { name: 'Dr. Raju K', position: 'Associate Professor', image: 't9' },
  { name: 'Dr. Anisha P Rodrigues', position: 'Associate Professor', image: 't10' },
  { name: 'Dr. Pallavi K N', position: 'Associate Professor', image: 't11' },
  { name: 'Dr. Sannidhan M S', position: 'Associate Professor', image: 't12' },
  { name: 'Dr. Sandeep Kumar Hegde', position: 'Associate Professor', image: 't13' },
  { name: 'Dr. Shabari Shedthi B', position: 'Associate Professor', image: 't14' },
  { name: 'Dr. Raghunandan K R', position: 'Associate Professor', image: 't15' },
  { name: 'Dr. Rajalaxmi Hegde', position: 'Associate Professor', image: 't16' },
  { name: 'Dr. Vijaya Murari T', position: 'Associate Professor', image: 't17' },
  { name: 'Dr. Pradeep Kanchan', position: 'Assistant Professor Gd-III', image: 't18' },
  { name: 'Dr. Keerthana B Chigateri', position: 'Assistant Professor Gd-III', image: 't19' },
  { name: 'Mr. Guru Prasad', position: 'Assistant Professor Gd-III', image: 't20' },
  { name: 'Dr. Shashank Shetty', position: 'Assistant Professor Gd-III', image: 't21' },
  { name: 'Dr. Asmita Poojary', position: 'Assistant Professor Gd-III', image: 't22' },
  { name: 'Ms. Minu P Abhraham', position: 'Assistant Professor Gd-II', image: 't23' },
  { name: 'Mr. Samapath Kini', position: 'Assistant Professor Gd-II', image: 't24' },
  { name: 'Mr. Pawan Hegde', position: 'Assistant Professor Gd-II', image: 't25' },
  { name: 'Ms. Shwetha G K', position: 'Assistant Professor Gd-II', image: 't26' },
  { name: 'Ms. Savitha Shetty', position: 'Assistant Professor Gd-II', image: 't27' },
  { name: 'Mr. Puneeth R P', position: 'Assistant Professor Gd-II', image: 't28' },
  { name: 'Ms. Manasa G R', position: 'Assistant Professor Gd-II', image: 't29' },
  { name: 'Mr. Sunil Kumar Aithal S', position: 'Assistant Professor Gd-II', image: 't30' },
  { name: 'Ms. Ankitha A Nayak', position: 'Assistant Professor Gd-II', image: 't31' },
  { name: 'Mr. Ashwin Shenoy', position: 'Assistant Professor Gd-II', image: 't32' },
  { name: 'Mrs. Shilpa Karegoudkar', position: 'Assistant Professor Gd-II', image: 't33' },
  { name: 'Mrs. Sowmya P', position: 'Assistant Professor Gd-II', image: 't34' },
  { name: 'Mr. Akhilraj V Gadagkar', position: 'Assistant Professor Gd-II', image: 't35' },
  { name: 'Ms. Jayapadmini Kanchan', position: 'Assistant Professor Gd-II', image: 't36' },
  { name: 'Mr. Prithviraj Jain', position: 'Assistant Professor Gd-II', image: 't37' },
  { name: 'Ms. Sowmya S', position: 'Assistant Professor Gd-II', image: 't38' },
  { name: 'Ms. Rajashree', position: 'Assistant Professor Gd-I', image: 't39' },
  { name: 'Ms. Joylin Priya Pinto', position: 'Assistant Professor Gd-I', image: 't40' },
  { name: 'Ms. Anusha Anchan', position: 'Assistant Professor Gd-I', image: 't41' },
  { name: 'Ms. Aishwarya D Shetty', position: 'Assistant Professor Gd-I', image: 't42' },
  { name: 'Mrs. Soumya Ashwath', position: 'Assistant Professor Gd-I', image: 't43' },
  { name: 'Ms. Vaishali Bangera', position: 'Assistant Professor Gd-I', image: 't44' },
  { name: 'Ms. Anupama H C', position: 'Assistant Professor Gd-I', image: 't45' },
];

export const teamMembers = {
  2023: [
    { name: 'Vasudha G', position: 'President', image: 'President-min' },
    { name: 'Keerthan Samuel Jathannna', position: 'Branch Captian', image: 'ABI03955-min' },
    { name: 'Saurabh Sunish', position: 'Vice President', image: 'ABI03875-min' },
    { name: 'Tvisha Prakash', position: 'Branch Secretary', image: 'ABI03882-min' },
    { name: 'Shannon Vianny Vas', position: 'Treasurer', image: 'ABI03877-min' },
    { name: 'Lisha Anni Rodrigues', position: 'Joint Secretary', image: 'lisha-min' },
    { name: 'Driksha Hegde', position: 'Social Event Coordinator', image: 'ABI04166-min' },
    { name: 'Kritharth', position: 'Social Event Coordinator', image: 'ABI03894-min' },
    { name: 'Sanjana R Shet', position: 'Cultural Secretary', image: 'ABI03900-min' },
    { name: 'Ananya', position: 'Cultural Secretary', image: 'ABI04159-min' },
    { name: 'Pearl Menezes', position: 'Magazine Coordinator', image: 'ABI04162-min' },
    { name: 'Siya Shetty', position: 'Magazine Coordinator', image: 'ABI03924-min' },
    { name: 'Gahana Shetty', position: 'Magazine Coordinator', image: 'ABI03891-min' },
    { name: 'Carol Dcunha', position: 'Magazine Coordinator', image: 'ABI04170-min' },
    { name: 'Navaraj D Shetty', position: 'Sports Coordinator', image: 'navaraj-min' },
    { name: 'Thashwin Shreevatsa', position: 'Sports Coordinator', image: 'thaswin-min' },
    { name: 'Chirag B S', position: 'Graphic Design Coordinator', image: 'ABI03908-min' },
    { name: 'Srilaxmi Bhagawath', position: 'Graphic Design Coordinator', image: 'ABI04135-min' },
    { name: 'Preethika Shet', position: 'Social Media Coordinator', image: 'ABI04132-min' },
    { name: 'Anaksha N A', position: 'Social Media Coordinator', image: 'ABI03903-min' },
    { name: 'Prathamesh Hebbar', position: 'Joint Social Media Coordinator', image: 'pratamesh-min' },
    { name: 'Sagar Kotian', position: 'Joint-Social Media Coordinator', image: 'ABI04477-min' },
    { name: 'Rohan MP', position: 'Technical Coordinator', image: 'ABI03974-min' },
    { name: 'Satwik Prabhu', position: 'Techincal Coordinator', image: 'ABI03897-min' },
    { name: 'Len Mendonca', position: 'Joint Technical Coordinator', image: 'ABI04492-min' },
    //why is his name not in teams
    // { name: 'Varun Pai', position: 'Joint Technical Coordinator', image: '/images/developers/varunpai.jpeg' },
    { name: 'Omkar', position: 'Joint Graphics Design Coordinator', image: 'ABI04469-min' },
    { name: 'Pratham Nayak', position: 'Joint Graphics Design Coordinator', image: 'ABI04475-min' },
    { name: 'Akhil Manoj', position: 'Joint Graphics Design Coordinator', image: 'ABI04467-min' },
    { name: 'Harshit D Shettigar', position: 'Joint Cultural Coordinator', image: 'ABI04436-min' },
    {
      name: 'Sanjana Santhosh Gunaga',
      position: 'Joint Cultural Coordinator',
      image: 'ABI04440-min',
    },
    { name: 'Pratheek A Shetty', position: 'Joint Sports Coordinator', image: 'ABI04456-min' },
    { name: 'Siona Angela Rodrigues', position: 'Joint Sports Coordinator', image: 'ABI04452-min' },
    { name: 'N Liya Nanaiah', position: 'Joint Magazine Coordinator', image: 'ABI04504-min' },
    { name: 'Sujan Amin', position: 'Joint Social Event Coordinator', image: 'ABI04462-min' },
    {
      name: 'Sakshi Sujit Shetty',
      position: 'Joint Social Event Coordinator',
      image: 'ABI04459-min',
    },
    {
      name: 'Kaniel Bion Almeida',
      position: 'Photography & Video Coordinator',
      image: 'ABI04141-min',
    },
    { name: 'S Abishek', position: 'Photography & Video Coordinator', image: 'ABI03962-min' },
    { name: 'Athul N Rao', position: 'Joint Photography & Video Coordinator', image: 'ABI04489-min' },
    {
      name: 'B Gautam Mohan',
      position: 'Joint Photography & Video Coordinator',
      image: 'ABI04484-min',
    },
  ],
  2024: [
    { name: 'U Sai Vikram', position: 'President', image: 'Sai Vikram_President' },
    { name: 'Aaric Johan Rodrigues', position: 'Vice President', image: 'Aaric Johan Rodrigues - Vice President' },
    { name: 'Tejas Jain', position: 'Branch Captain', image: 'TEJAS JAIN' },
    { name: 'Hebbar Prathamesh', position: 'Branch secretary', image: 'Hebbar Prathamesh branch secretary ' },
    { name: 'Varun suresh', position: 'Treasurer', image: 'Varun Shetty_Treasurer' },
    { name: 'Liya Nanaiah', position: 'join secretary', image: 'sample' },
    { name: 'Harshith D S', position: 'Cultural Secretary', image: 'HarshithDS_CulturalSecretary' },
    { name: 'Aastha Nikin Shetty', position: 'Cultural Secretary', image: 'AasthaNikinShetty_culturalsecretary' },
    { name: 'Len Danieo Thomas Mendonca', position: 'Technical cordinator', image: 'Len-technicalLead' },
    { name: 'Chinmayee Bhat', position: 'Technical cordinator', image: 'CHINMAYEE BHAT_Technical Lead' },
    { name: 'Chinmay Dinesh Billava', position: 'Technical cordinator', image: 'Chinmay Dinesh Billava_Technical Coordinator' },
    { name: 'Diya R Kamath', position: 'Sports Coordinator', image: 'Diya R Kamath_Sports Coordinator' },
    { name: 'Abhi S Kamath', position: 'Sports Coordinator', image: 'Abhi S Kamath - Sports Coordinator_' },
    { name: 'Dilshan Divan Dsouza', position: 'Sports Coordinator', image: 'Dilshan Dsouza_Sports Coordinator' },
    { name: 'Jovian Rodrigues', position: 'Sports Coordinator', image: 'sample' },
    { name: 'Amrutha R Rao', position: 'Magazine Coordinator', image: 'Amrutha R Rao_Magazine coordinator_' },
    { name: 'Disha Budale', position: 'Magazine Coordinator', image: 'Disha Budale_MagazineCoordinator' },
    { name: 'Sanjana Santosh Gunaga', position: 'Magazine Coordinator', image: 'Sanjana Gunaga_Magazine Coordinator_page-0001' },
    { name: 'K Shailesh Rao', position: 'Magazine Coordinator', image: 'K Shailesh Rao_MagazineCoordinator' },
    { name: 'Riya S Shetty', position: 'Magazine Coordinator', image: 'Riya S Shetty_Magazine Coordinator' },
    { name: 'Pratham Sridasa Nayak', position: 'Social Event Coordinator', image: 'Pratham Sridas Nayak_Social Event Coordinator_' },
    { name: 'Shetty Sakshi Sujit', position: 'Social Event Coordinator', image: 'Shetty Sakshi Sujit_Social Event Coordinator' },
    { name: 'Charith', position: 'Social Event Coordinator', image: 'Charith-Social Event Coordinator' },
    { name: 'Vaishnavi Kamath', position: 'Social Event Coordinator', image: 'Vaishnavi Kamath_Social Event Coordinator_' },
    { name: 'Karthick Ail', position: 'Graphics Design Coordinator', image: 'Karthik Ail_Main Graphic design Coordinator_' },
    { name: 'Omkar Arun Sanil', position: 'Graphics Design Coordinator', image: 'sample' },
    { name: 'Athul N Rao', position: 'Photography & Video Coordinator', image: 'Athul N Rao_Photography and Videography coordinator_' },
    { name: 'Arkal Varun Hegde', position: 'Photography & Video Coordinator', image: 'Arkal Varun Hegde Photography & Video' },
    { name: 'Shifali Mada', position: 'Social Media Coordinator', image: 'Shifali mada-social media coordinator' },
    { name: 'Paras Savera', position: 'Social Media Coordinator', image: 'Paras savera Social media coordinator' },
    { name: 'Abhiram N udupa', position: 'Jt cultural secretary', image: 'Abhiram N Udupa_JointCulturalSecretary' },
    { name: 'Namana B K', position: 'Jt cultural secretary', image: 'Namana B K _ Joint Cultural Coordinator_' },
    { name: 'Aston Prince  Mathias', position: 'Jt Technical coordinator', image: 'Ashton Mathias_Joint Technical Coordinator' },
    { name: 'Moulya shetty', position: 'Jt sports Coordinator', image: 'Moulya Shetty_Joint sports coordinator' },
    { name: 'Janvi Hegde', position: 'Jt magazine Coordinator', image: 'Janvi Hegde _ Joint magazine coordinator' },
    { name: 'Poorvi Kalyani', position: 'Jt magazine Coordinator', image: 'POORVI KALYANI_joint magazine coordinator' },
    { name: 'Samuel Rodrigues', position: 'Jt social event Coordinator', image: 'Samuel Rodrigues _Joint Social Event Coordinator_' },
    { name: 'Adithi H Nayak', position: 'Graphic design Coordinator', image: 'Aditi H Nayak_Joint Graphics Design Coordinator' },
    { name: 'Krithi', position: 'Graphic design Coordinator', image: 'Krithi_JointGraphicsDesignCoordinator' },
    { name: 'Shashwath J Shetty', position: 'Jt Photography and videography Coordinator', image: 'Shashwath J Shetty_Joint Photography & Videography Coordinator' },
    { name: 'Sujan S', position: 'Jt Social Media Coordinator', image: 'Sujan S- Joint social media coordinator_' },
    { name: 'Rachana Narayan', position: 'Jt Social Media Coordinator', image: 'Rachana_joint social media coordinator' },
  ],
  faculty,
};

import KarthikImage from '@assets/images/developers/karthik.webp';
import varunPaiImage from '@assets/images/developers/varunpai.webp';
import varshithPawarImage from '@assets/images/developers/varshith.webp';
import akhilImage from '@assets/images/developers/akhil.webp';
import ameeshaImage from '@assets/images/developers/ameesha.webp';
import sampleImage from '@assets/images/sample.png';

export const testimonials = [
  { name: 'Karthik', message: '@Varshith layout fixed; If they give attendence im in', imageUrl: KarthikImage },
  {
    name: 'Avaneesh',
    message: 'If youre into solving probs and building sick stuff, this is where the magic happens!',
    imageUrl: sampleImage,
  },
  { name: 'Shashank B N', message: 'Use VIM', imageUrl: sampleImage },
  { name: 'Satwik Prabhu', message: 'i know where you live', imageUrl: sampleImage },
  { name: 'wisdom--1', message: 'Fullfill 85% attendance criteria', imageUrl: sampleImage },
  { name: 'Unknown', message: 'Satwik Prabhu is a cutie', imageUrl: sampleImage },
  {
    name: 'Vasudha Bhat',
    message:
      'Association of Computer Engineers (ACE ) is a dedicated organisation for Computer Science department.  Dedicated organisation that helps students to develop both Technical and non-technical skills including Sports. It was always great working with ACE. Thanks for the opportunity',
    imageUrl: sampleImage,
  },
  {
    name: 'Varshith Pawar H R',
    message: ' y I did this format-visit : https://orm.drizzle.team/',
    imageUrl: varshithPawarImage,
  },
  { name: 'akhil', message: 'will never know!!', imageUrl: akhilImage },
  {
    name: 'Prashasti Pandey',
    message:
      'ACE was an amazing experience at nitte, right from starting the face space to sitting at the budget meetings for our incridea events , from organising Improv to making rangolis for ayudh puja from planning freshers to receiving our farewell, we shared good memories . P.S. youll always be good books of every proff.  Also , plan your events before that one branch implements it ;)m?',
    imageUrl: sampleImage,
  },
  { name: 'Varun pai', message: 'Learn Flutter', imageUrl: varunPaiImage },
  { name: 'Ameesha', message: 'Work more on your side projects ', imageUrl: ameeshaImage },
];
