export const SITE_TITLE = 'Ace Website';
export const SITE_DESCRIPTION = 'Welcome to Ace Website';

export enum ContentType {
  CardLink = 'card-link',
  Video = 'video',
  None = 'none',
}

export const githubLink = 'https://github.com/ACE-NMAMIT/';
export const linkedinLink = 'https://www.linkedin.com/company/acenmamit/';
export const instagramLink = 'https://www.instagram.com/ace_nmamit/';

export const faculty = [
  { name: 'Dr. Niranjan N. Chiplunkar', position: 'Principal', image: 'prin' },
  { name: 'Dr. Jyothi Shetty', position: 'Professor & Head', image: 'hod' },
  { name: 'Mr. Piyush Goel', position: 'Pofessor of Practice', image: 't3' },
  { name: 'Dr. D K Sreekantha', position: 'Professor', image: 't4' },
  { name: 'Dr. P V Bhat ', position: 'Professor', image: 't5' },
  { name: 'Dr. Aravind C V', position: 'Professor', image: 't6' },
  { name: 'Dr. Sarika Hegde', position: 'Professor', image: 't7' },
  { name: 'Dr. Sudeepa K B', position: 'Associate Professor', image: 't8' },
  { name: 'Dr. Raju K', position: 'Associate Professor', image: 't9' },
  { name: 'Dr. Anisha P Rodrigues', position: 'Associate Professor', image: 't10' },
  { name: 'Dr. Pallavi K N', position: 'Associate Professor', image: 't11' },
  { name: 'Dr. Sannidhan M S', position: 'Associate Professor', image: 't12' },
  { name: 'Dr. Sandeep Kumar Hegde', position: 'Associate Professor', image: 't13' },
  { name: 'Dr. Shabari Shedthi B', position: 'Associate Professor', image: 't14' },
  { name: 'Dr. Raghunandan K R', position: 'Associate Professor', image: 't15' },
  { name: 'Dr. Rajalaxmi Hegde', position: 'Associate Professor', image: 't16' },
  { name: 'Dr. Vijaya Murari T', position: 'Associate Professor', image: 't17' },
  { name: 'Dr. Pradeep Kanchan', position: 'Assistant Professor Gd-III', image: 't18' },
  { name: 'Dr. Keerthana B Chigateri', position: 'Assistant Professor Gd-III', image: 't19' },
  { name: 'Mr. Guru Prasad', position: 'Assistant Professor Gd-III', image: 't20' },
  { name: 'Dr. Shashank Shetty', position: 'Assistant Professor Gd-III', image: 't21' },
  { name: 'Dr. Asmita Poojary', position: 'Assistant Professor Gd-III', image: 't22' },
  { name: 'Ms. Minu P Abhraham', position: 'Assistant Professor Gd-II', image: 't23' },
  { name: 'Mr. Samapath Kini', position: 'Assistant Professor Gd-II', image: 't24' },
  { name: 'Mr. Pawan Hegde', position: 'Assistant Professor Gd-II', image: 't25' },
  { name: 'Ms. Shwetha G K', position: 'Assistant Professor Gd-II', image: 't26' },
  { name: 'Ms. Savitha Shetty', position: 'Assistant Professor Gd-II', image: 't27' },
  { name: 'Mr. Puneeth R P', position: 'Assistant Professor Gd-II', image: 't28' },
  { name: 'Ms. Manasa G R', position: 'Assistant Professor Gd-II', image: 't29' },
  { name: 'Mr. Sunil Kumar Aithal S', position: 'Assistant Professor Gd-II', image: 't30' },
  { name: 'Ms. Ankitha A Nayak', position: 'Assistant Professor Gd-II', image: 't31' },
  { name: 'Mr. Ashwin Shenoy', position: 'Assistant Professor Gd-II', image: 't32' },
  { name: 'Mrs. Shilpa Karegoudkar', position: 'Assistant Professor Gd-II', image: 't33' },
  { name: 'Mrs. Sowmya P', position: 'Assistant Professor Gd-II', image: 't34' },
  { name: 'Mr. Akhilraj V Gadagkar', position: 'Assistant Professor Gd-II', image: 't35' },
  { name: 'Ms. Jayapadmini Kanchan', position: 'Assistant Professor Gd-II', image: 't36' },
  { name: 'Mr. Prithviraj Jain', position: 'Assistant Professor Gd-II', image: 't37' },
  { name: 'Ms. Sowmya S', position: 'Assistant Professor Gd-II', image: 't38' },
  { name: 'Ms. Rajashree', position: 'Assistant Professor Gd-I', image: 't39' },
  { name: 'Ms. Joylin Priya Pinto', position: 'Assistant Professor Gd-I', image: 't40' },
  { name: 'Ms. Anusha Anchan', position: 'Assistant Professor Gd-I', image: 't41' },
  { name: 'Ms. Aishwarya D Shetty', position: 'Assistant Professor Gd-I', image: 't42' },
  { name: 'Mrs. Soumya Ashwath', position: 'Assistant Professor Gd-I', image: 't43' },
  { name: 'Ms. Vaishali Bangera', position: 'Assistant Professor Gd-I', image: 't44' },
  { name: 'Ms. Anupama H C', position: 'Assistant Professor Gd-I', image: 't45' },
];


export const teamMembers = {
  2023: [
    { name: 'Vasudha G', position: 'President', image: 'President-min' },
    { name: 'Keerthan Samuel Jathannna', position: 'Branch Captian', image: 'ABI03955-min' },
    { name: 'Saurabh Sunish', position: 'Vice President', image: 'ABI03875-min' },
    { name: 'Tvisha Prakash', position: 'Branch Secretary', image: 'ABI03882-min' },
    { name: 'Shannon Vianny Vas', position: 'Treasurer', image: 'ABI03877-min' },
    { name: 'Lisha Anni Rodrigues', position: 'Joint Secretary', image: 'lisha-min' },
    { name: 'Driksha Hegde', position: 'Social Event Coordinator', image: 'ABI04166-min' },
    { name: 'Kritharth', position: 'Social Event Coordinator', image: 'ABI03894-min' },
    { name: 'Sanjana R Shet', position: 'Cultural Secretary', image: 'ABI03900-min' },
    { name: 'Ananya', position: 'Cultural Secretary', image: 'ABI04159-min' },
    { name: 'Pearl Menezes', position: 'Magazine Coordinator', image: 'ABI04162-min' },
    { name: 'Siya Shetty', position: 'Magazine Coordinator', image: 'ABI03924-min' },
    { name: 'Gahana Shetty', position: 'Magazine Coordinator', image: 'ABI03891-min' },
    { name: 'Carol Dcunha', position: 'Magazine Coordinator', image: 'ABI04170-min' },
    { name: 'Navaraj D Shetty', position: 'Sports Coordinator', image: 'navaraj-min' },
    { name: 'Thashwin Shreevatsa', position: 'Sports Coordinator', image: 'thaswin-min' },
    { name: 'Chirag B S', position: 'Graphic Design Coordinator', image: 'ABI03908-min' },
    { name: 'Srilaxmi Bhagawath', position: 'Graphic Design Coordinator', image: 'ABI04135-min' },
    { name: 'Preethika Shet', position: 'Social Media Coordinator', image: 'ABI04132-min' },
    { name: 'Anaksha N A', position: 'Social Media Coordinator', image: 'ABI03903-min' },
    { name: 'Prathamesh Hebbar', position: 'Joint Social Media Coordinator', image: 'pratamesh-min' },
    { name: 'Sagar Kotian', position: 'Joint-Social Media Coordinator', image: 'ABI04477-min' },
    { name: 'Rohan MP', position: 'Technical Coordinator', image: 'ABI03974-min' },
    { name: 'Satwik Prabhu', position: 'Techincal Coordinator', image: 'ABI03897-min' },
    { name: 'Len Mendonca', position: 'Joint Technical Coordinator', image: 'ABI04492-min' },
    //why is his name not in teams
    // { name: 'Varun Pai', position: 'Joint Technical Coordinator', image: '/images/developers/varunpai.jpeg' },
    { name: 'Omkar', position: 'Joint Graphics Design Coordinator', image: 'ABI04469-min' },
    { name: 'Pratham Nayak', position: 'Joint Graphics Design Coordinator', image: 'ABI04475-min' },
    { name: 'Akhil Manoj', position: 'Joint Graphics Design Coordinator', image: 'ABI04467-min' },
    { name: 'Harshit D Shettigar', position: 'Joint Cultural Coordinator', image: 'ABI04436-min' },
    {
      name: 'Sanjana Santhosh Gunaga',
      position: 'Joint Cultural Coordinator',
      image: 'ABI04440-min',
    },
    { name: 'Pratheek A Shetty', position: 'Joint Sports Coordinator', image: 'ABI04456-min' },
    { name: 'Siona Angela Rodrigues', position: 'Joint Sports Coordinator', image: 'ABI04452-min' },
    { name: 'N Liya Nanaiah', position: 'Joint Magazine Coordinator', image: 'ABI04504-min' },
    { name: 'Sujan Amin', position: 'Joint Social Event Coordinator', image: 'ABI04462-min' },
    {
      name: 'Sakshi Sujit Shetty',
      position: 'Joint Social Event Coordinator',
      image: 'ABI04459-min',
    },
    {
      name: 'Kaniel Bion Almeida',
      position: 'Photography & Video Coordinator',
      image: 'ABI04141-min',
    },
    { name: 'S Abishek', position: 'Photography & Video Coordinator', image: 'ABI03962-min' },
    { name: 'Athul N Rao', position: 'Joint Photography & Video Coordinator', image: 'ABI04489-min' },
    {
      name: 'B Gautam Mohan',
      position: 'Joint Photography & Video Coordinator',
      image: 'ABI04484-min',
    },
  ],
  2024: [],
  faculty,
};